### ISSUE TITLE
Missing images and CSS

### ISSUE THREAD

**Issue by player1537** [FRC-Team-3140/Website2015#1]
I tried loading this on my computer, but I'm missing the images and styles. I've included what my developer console on Chrome says (which gives a list of all the files that are missing). You should just have to run the command `git add Images/*.png Images/*.jpg styles.css sliderstyle.css`.

![screen shot 2016-07-14 at 2 21 25 pm](https://cloud.githubusercontent.com/assets/1215969/16850679/4372564e-49ce-11e6-91dd-1ee7e2c56d09.png)

**Comment by ajc14654** [comment]
Are you accessing the files from the folder labeled “Website" or not? Because it worked for me when I accessed the webpages that way.
    -Adam

**Comment by ajc14654** [comment]
Just a heads-up: I got a new laptop, and have nothing downloaded yet, so I probably won’t be able to work on the laptop for a day or two.
    -Adam

**Comment by player1537** [comment]
Cheers, that fixed it. It might be good to add that to the readme. 

I was trying to load the files from the root directory, in the master and then dev branches.
